// Code generated by mockery v2.42.0. DO NOT EDIT.

package mocks

import (
	entity "github.com/deBeloper-code/goFinance/internal/pkg/entity"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// DepositRepository is an autogenerated mock type for the DepositRepository type
type DepositRepository struct {
	mock.Mock
}

// AddDeposit provides a mock function with given fields: deposit
func (_m *DepositRepository) AddDeposit(deposit *entity.Deposit) error {
	ret := _m.Called(deposit)

	if len(ret) == 0 {
		panic("no return value specified for AddDeposit")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*entity.Deposit) error); ok {
		r0 = rf(deposit)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetUserDeposit provides a mock function with given fields: userID, startDate, endDate
func (_m *DepositRepository) GetUserDeposit(userID string, startDate time.Time, endDate time.Time) ([]*entity.Deposit, error) {
	ret := _m.Called(userID, startDate, endDate)

	if len(ret) == 0 {
		panic("no return value specified for GetUserDeposit")
	}

	var r0 []*entity.Deposit
	var r1 error
	if rf, ok := ret.Get(0).(func(string, time.Time, time.Time) ([]*entity.Deposit, error)); ok {
		return rf(userID, startDate, endDate)
	}
	if rf, ok := ret.Get(0).(func(string, time.Time, time.Time) []*entity.Deposit); ok {
		r0 = rf(userID, startDate, endDate)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Deposit)
		}
	}

	if rf, ok := ret.Get(1).(func(string, time.Time, time.Time) error); ok {
		r1 = rf(userID, startDate, endDate)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewDepositRepository creates a new instance of DepositRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDepositRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *DepositRepository {
	mock := &DepositRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
